collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.5789486
color:
  saturation: 0.5032649
  brandStrength: 0.4519723
  rhythmicContrast: 0.7318097
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  lightness: 0.7770522
layout_spectrum: 0.9836754
name: Jasonbmarley
