layout_spectrum: 0.06623134
typography_spectrum: 0.5789486
color:
  saturation: 0.5032649
  brandStrength: 0.4519723
  lightness: 0.7770522
  rhythmicContrast: 0.7318097
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: Jasonbmarley
